/**
 * Converte Playwright storage state (sessions/PLATFORM-USER.json)
 * para Netscape cookies.txt format que o yt-dlp consome.
 */
import fs from 'fs'
import path from 'path'

export function writeCookiesTxt(sessionFile, outFile) {
  if (!fs.existsSync(sessionFile)) throw new Error(`Sessao nao encontrada: ${sessionFile}`)
  const state = JSON.parse(fs.readFileSync(sessionFile, 'utf-8'))
  const cookies = state.cookies || []
  const lines = ['# Netscape HTTP Cookie File', '# Generated by PostMaster', '']
  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : `.${(c.domain || '').replace(/^www\./, '')}`
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const cpath = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expires = Math.floor(c.expires && c.expires > 0 ? c.expires : (Date.now()/1000 + 365*86400))
    lines.push(`${domain}\t${flag}\t${cpath}\t${secure}\t${expires}\t${c.name}\t${c.value}`)
  }
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, lines.join('\n'), 'utf-8')
  return outFile
}

// Pega o cookies.txt de qualquer conta logada da plataforma (primeira encontrada)
export function getCookiesForPlatform(platform, dataDir) {
  const prefix = platform === 'instagram' ? 'ig'
               : platform === 'tiktok'    ? 'tk'
               : platform === 'youtube'   ? 'yt'
               : null
  if (!prefix) return null
  const sessionsDir = path.join(dataDir, 'sessions')
  if (!fs.existsSync(sessionsDir)) return null
  const files = fs.readdirSync(sessionsDir).filter(f => f.startsWith(`${prefix}-`) && f.endsWith('.json'))
  if (!files.length) return null
  const sessionFile = path.join(sessionsDir, files[0])
  const cookiesTxt = path.join(sessionsDir, files[0].replace('.json', '-cookies.txt'))
  // Re-gera sempre (cookies podem ter sido renovados pelo poster)
  try { writeCookiesTxt(sessionFile, cookiesTxt); return cookiesTxt } catch { return null }
}
