/**
 * Login YouTube via Playwright (NAO via BrowserWindow Electron).
 * Google bloqueia janelas Electron com "Nao foi possivel fazer o login" mesmo com UA spoof.
 * Playwright Chromium passa pelo check porque eh Chrome real.
 */

import { chromium } from 'playwright'
import path from 'path'
import fs from 'fs'
import { getChromiumExe } from './playwrightExe.mjs'

const LOGIN_TIMEOUT_MS = 5 * 60 * 1000

export async function loginYouTubeViaPlaywright({ username, dataDir }) {
  const sessionFile = path.join(dataDir, 'sessions', `yt-${username}.json`)
  const cookiesTxt  = path.join(dataDir, 'sessions', `yt-cookies-${username}.txt`)
  const profileDir  = path.join(dataDir, 'sessions', `yt-${username}-profile`)
  fs.mkdirSync(profileDir, { recursive: true })

  const ctx = await chromium.launchPersistentContext(profileDir, {
    headless: false,
    executablePath: getChromiumExe() || undefined,
    args: [
      '--no-sandbox',
      '--disable-blink-features=AutomationControlled',
      '--disable-infobars',
    ],
    viewport: { width: 1280, height: 800 },
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
  })

  await ctx.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => undefined })
    // Fake window.chrome (Google verifica)
    if (!window.chrome) window.chrome = { runtime: {}, app: { isInstalled: false } }
    // Plugins fake
    Object.defineProperty(navigator, 'plugins', { get: () => [{ name: 'Chrome PDF Plugin' }] })
    Object.defineProperty(navigator, 'languages', { get: () => ['pt-BR', 'pt', 'en'] })
  })

  const page = ctx.pages()[0] || await ctx.newPage()

  await page.goto('https://www.youtube.com/', { waitUntil: 'domcontentloaded' })

  // Aguarda o user fazer login (cookies de auth aparecerem)
  return await new Promise((resolve, reject) => {
    let settled = false

    const timer = setTimeout(() => {
      if (settled) return
      settled = true
      cleanup().then(() => reject(new Error('Tempo esgotado — login nao concluido em 5 minutos.')))
    }, LOGIN_TIMEOUT_MS)

    async function cleanup() {
      clearTimeout(timer)
      try { await ctx.close() } catch {}
    }

    // Polling: a cada 2s checa se tem cookie de auth
    const poll = setInterval(async () => {
      if (settled) return
      try {
        const cookies = await ctx.cookies()
        const logged = cookies.some(c =>
          (c.domain.includes('youtube.com') && c.name === 'LOGIN_INFO') ||
          (c.domain.includes('google.com') && c.name === 'SAPISID')
        )
        if (!logged) return

        // Logado! Aguarda mais 1.5s pra estabilizar cookies, depois salva
        await new Promise(r => setTimeout(r, 1500))
        const finalCookies = await ctx.cookies()
        await saveStorageState(ctx, finalCookies, sessionFile)
        await saveCookiesNetscape(finalCookies, cookiesTxt)

        settled = true
        clearInterval(poll)
        await cleanup()
        resolve({ ok: true, sessionFile, cookiesTxt })
      } catch (e) {
        // Pagina pode ter sido fechada — verifica
        if (e.message?.includes('Target page, context or browser has been closed')) {
          if (settled) return
          settled = true
          clearInterval(poll)
          clearTimeout(timer)
          reject(new Error('Janela de login fechada antes de concluir'))
        }
      }
    }, 2000)
  })
}

async function saveStorageState(ctx, cookies, outFile) {
  const state = {
    cookies: cookies.map(c => ({
      name: c.name, value: c.value, domain: c.domain, path: c.path || '/',
      expires: c.expires || -1, httpOnly: !!c.httpOnly, secure: !!c.secure,
      sameSite: c.sameSite || 'Lax',
    })),
    origins: [],
  }
  fs.writeFileSync(outFile, JSON.stringify(state, null, 2))
}

// Netscape cookies.txt format pro yt-dlp consumir
async function saveCookiesNetscape(cookies, outFile) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by PostMaster', '']
  for (const c of cookies) {
    if (!c.domain.match(/google|youtube/i)) continue
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain.replace(/^www\./, '')}`
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const cpath = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expires = Math.floor(c.expires || (Date.now()/1000 + 365*86400))
    lines.push(`${domain}\t${flag}\t${cpath}\t${secure}\t${expires}\t${c.name}\t${c.value}`)
  }
  fs.writeFileSync(outFile, lines.join('\n'), 'utf-8')
}
