/**
 * Login via janela nativa do Electron (sem Playwright).
 * Mais estavel pra usuario final — Chromium da pra Electron e nao depende
 * do binario externo do Playwright para abrir.
 *
 * Estrategia:
 * 1. Abre BrowserWindow com URL de login
 * 2. Usuario loga normalmente
 * 3. Detecta sucesso quando URL muda pra fora de /login
 * 4. Pega cookies via session.cookies.get(...)
 * 5. Salva no formato Playwright storageState (compativel com poster.mjs)
 */

import path from 'path'
import fs from 'fs'

const LOGIN_TIMEOUT_MS = 5 * 60 * 1000 // 5 min

// Trava: nao permite 2 logins simultaneos pra mesma conta
const activeLogins = new Set()

export async function loginViaElectron({ platform, username, dataDir }) {
  const lockKey = `${platform}:${username}`
  if (activeLogins.has(lockKey)) {
    throw new Error(`Login para @${username} já está em andamento — feche a janela existente primeiro.`)
  }
  activeLogins.add(lockKey)
  try {
    // v1.0.70: YouTube via Playwright + Chrome REAL do sistema.
    // Google blacklistou Electron + Chromium puro. Chrome real passa.
    if (platform === 'youtube') {
      return await doLoginYouTubeViaChrome({ username, dataDir })
    }
    return await doLogin({ platform, username, dataDir })
  } finally {
    activeLogins.delete(lockKey)
  }
}

// v1.0.70: Login YouTube via Chrome REAL do sistema. Google detecta e bloqueia
// Electron + Chromium custom, mas aceita Chrome legítimo. Usa Playwright
// launchPersistentContext com channel: 'chrome'.
// v1.0.73: converte cookies do Playwright storageState pra Netscape format
// (yt-cookies-{conta}.txt) pra yt-dlp poder usar a MESMA conta pra baixar.
// Assim 1 login = 1 conta que serve pra postar E baixar (antes era 2 contas).
async function exportCookiesNetscape(storageStateFile, txtFile) {
  try {
    const state = JSON.parse(fs.readFileSync(storageStateFile, 'utf-8'))
    const lines = ['# Netscape HTTP Cookie File', '# Generated by PostMaster login', '']
    for (const c of (state.cookies || [])) {
      // Filtra so cookies relevantes (google + youtube)
      if (!/google\.com|youtube\.com/.test(c.domain)) continue
      lines.push([
        c.domain,
        c.domain.startsWith('.') ? 'TRUE' : 'FALSE',
        c.path || '/',
        c.secure ? 'TRUE' : 'FALSE',
        c.expires && c.expires > 0 ? Math.floor(c.expires) : 0,
        c.name,
        c.value,
      ].join('\t'))
    }
    fs.writeFileSync(txtFile, lines.join('\n'))
    return true
  } catch (e) {
    console.error('[login-yt] exportCookiesNetscape:', e.message)
    return false
  }
}

async function doLoginYouTubeViaChrome({ username, dataDir }) {
  const { chromium } = await import('playwright')
  const os = await import('node:os')
  const sessionFile = path.join(dataDir, 'sessions', `yt-${username}.json`)
  const cookiesTxtFile = path.join(dataDir, 'sessions', `yt-cookies-${username}.txt`)
  fs.mkdirSync(path.dirname(sessionFile), { recursive: true })

  const tmpProfile = path.join(os.tmpdir(), `pm-yt-login-${username}-${Date.now()}`)
  let ctx
  try {
    ctx = await chromium.launchPersistentContext(tmpProfile, {
      channel: 'chrome',
      headless: false,
      viewport: { width: 1280, height: 900 },
      locale: 'pt-BR',
      args: ['--no-sandbox', '--disable-blink-features=AutomationControlled'],
    })
  } catch (e) {
    throw new Error(`Chrome não encontrado no sistema. Instale o Google Chrome e tente de novo. (${e.message.slice(0,60)})`)
  }

  const page = await ctx.newPage()

  // v1.0.73: injeta banner explicativo no topo da pagina antes de qualquer
  // navegacao. Banner reforca: "FECHE quando estiver no canal certo".
  await ctx.addInitScript(() => {
    const showBanner = () => {
      if (document.getElementById('pm-login-banner')) return
      if (!document.body) return
      const b = document.createElement('div')
      b.id = 'pm-login-banner'
      b.style.cssText = 'position:fixed;top:0;left:0;right:0;z-index:2147483647;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;padding:14px 20px;font-family:Segoe UI,sans-serif;font-size:13px;display:flex;align-items:center;gap:14px;box-shadow:0 2px 12px rgba(0,0,0,.3)'
      b.innerHTML = '<span style="font-size:22px">📺</span><div style="flex:1"><strong style="font-size:14px">PostMaster: Login YouTube</strong><br><span style="opacity:.95;font-size:12px">1) Faça login com sua conta Google.<br>2) Se você tem MAIS DE UM CANAL, troque pelo menu da foto de perfil (canto superior direito) e escolha o canal que vai postar.<br>3) Quando estiver no canal certo, <strong>FECHE ESTA JANELA</strong> — o app vai pegar exatamente o canal que tá aberto.</span></div>'
      document.body.insertBefore(b, document.body.firstChild)
      document.body.style.paddingTop = '110px'
    }
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', showBanner)
    } else {
      showBanner()
    }
    // Reinjeta a cada 1s pq YouTube re-renderiza
    setInterval(showBanner, 1500)
  })

  await page.goto('https://studio.youtube.com/', { waitUntil: 'domcontentloaded', timeout: 60000 })

  // v1.0.73: aguarda user FECHAR a janela (em vez de detectar auto).
  // No momento que fecha, pega a URL ATUAL = canal escolhido.
  // v1.0.75: salva .channelId TODA vez que ve /channel/UCxxx na URL — assim
  // se user fechar em outra URL (settings, conta, etc) ainda temos o ultimo
  // canal visitado salvo. Antes so salvava no close → perdia se URL nao tinha.
  const channelIdFile = sessionFile.replace(/\.json$/, '.channelId')
  let lastChannelId = ''
  return new Promise(async (resolve, reject) => {
    let settled = false
    let lastUrl = ''
    const timeoutId = setTimeout(async () => {
      if (settled) return; settled = true
      try { await ctx.close() } catch {}
      reject(new Error('Tempo esgotado — login nao concluido em 10 minutos.'))
    }, 10 * 60 * 1000)

    // Polling pra capturar ultima URL antes de fechar
    const interval = setInterval(async () => {
      if (settled) return
      try {
        const pages = ctx.pages()
        if (pages.length === 0) {
          // User fechou todas as paginas
          settled = true
          clearTimeout(timeoutId); clearInterval(interval)
          // v1.0.75: se NUNCA viu /channel/UCxxx durante a sessao = nao logou
          if (!lastChannelId) {
            reject(new Error('Fechou sem passar pelo canal. Tente de novo e CLIQUE no canal certo no menu lateral antes de fechar.'))
            return
          }
          // v1.0.73: tb gera cookies Netscape pro yt-dlp usar a MESMA conta pra baixar
          await exportCookiesNetscape(sessionFile, cookiesTxtFile)
          resolve({ ok: true, sessionFile })
          return
        }
        const u = pages[0].url()
        if (u) {
          lastUrl = u
          // v1.0.75: ja salva channelId aqui (nao espera o close)
          const m = u.match(/studio\.youtube\.com\/channel\/(UC[\w-]+)/)
          if (m && m[1] !== lastChannelId) {
            lastChannelId = m[1]
            try { fs.writeFileSync(channelIdFile, m[1]) } catch {}
          }
        }
      } catch {}
    }, 1000)

    // Listener pra session.storageState — salva ANTES de fechar
    ctx.on('close', async () => {
      try { await ctx.storageState({ path: sessionFile }) } catch {}
    })
    // Salva tb periodicamente caso o close listener nao dispare
    const saveInterval = setInterval(async () => {
      if (settled) { clearInterval(saveInterval); return }
      try { await ctx.storageState({ path: sessionFile }) } catch {}
    }, 5000)
  })
}

async function doLogin({ platform, username, dataDir }) {
  const { BrowserWindow, session } = await import('electron')

  const sessionPrefix = platform === 'instagram' ? 'ig'
                      : platform === 'tiktok'    ? 'tk'
                      : platform === 'youtube'   ? 'yt'
                      : 'session'
  const isInsta = platform === 'instagram'
  const isYt    = platform === 'youtube'
  const sessionFile = path.join(dataDir, 'sessions', `${sessionPrefix}-${username}.json`)
  fs.mkdirSync(path.dirname(sessionFile), { recursive: true })

  // Particao isolada por conta — cookies nao misturam entre logins
  const partition = `persist:${sessionPrefix}-${username}`
  const ses = session.fromPartition(partition)
  // Limpa cookies antigos dessa conta antes de logar (evita tela "trocar de usuario")
  await ses.clearStorageData({ storages: ['cookies', 'localstorage', 'serviceworkers', 'cachestorage', 'shadercache', 'websql', 'indexdb'] })

  // YouTube: vai direto na home e o user clica "Fazer login" no proprio site.
  // Google bloqueia accounts.google.com em browser embedded (Erro 400).
  // Abrir youtube.com e clicar Sign In direto contorna a deteccao.
  const loginUrl = isInsta ? 'https://www.instagram.com/accounts/login/'
                 : isYt    ? 'https://www.youtube.com/'
                           : 'https://www.tiktok.com/login'

  const platformName = isInsta ? 'Instagram' : isYt ? 'Google/YouTube' : 'TikTok'

  // User-Agent de Chrome real — Google detecta Electron e bloqueia login (Erro 400).
  // Mesmo que loadURL passe direto pra youtube.com, qualquer redirect pra accounts.google.com
  // precisa de UA de Chrome legit pra nao bloquear.
  // v1.0.69: UA Chrome 132 (Google ja bloqueia 130 por ser "antigo"). Tambem
  // aplicamos Client Hints (sec-ch-ua) via webRequest pra parecer Chrome 100%.
  const REAL_CHROME_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'
  const SEC_CH_UA = '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"'

  const win = new BrowserWindow({
    width: 1080,
    height: 800,
    title: `Login ${platformName} — @${username}`,
    autoHideMenuBar: true,
    webPreferences: {
      partition,
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  // Override do User-Agent ANTES de qualquer load
  win.webContents.setUserAgent(REAL_CHROME_UA)
  ses.setUserAgent(REAL_CHROME_UA)

  // v1.0.69: Sobrescreve headers pra adicionar sec-ch-ua* (Client Hints) que
  // Google verifica pra detectar Electron/headless. Sem isso, mesmo com UA
  // Chrome, o login dá "Esse navegador ou app pode nao ser seguro".
  ses.webRequest.onBeforeSendHeaders((details, cb) => {
    const h = { ...details.requestHeaders }
    h['sec-ch-ua'] = SEC_CH_UA
    h['sec-ch-ua-mobile'] = '?0'
    h['sec-ch-ua-platform'] = '"Windows"'
    // Remove header que delata Electron
    delete h['Electron']
    delete h['electron']
    cb({ requestHeaders: h })
  })

  // v1.0.69: stealth JS — Google checa navigator.webdriver e propriedades
  // que Chromium puro nao tem. Sobrescreve antes de qualquer script da pagina.
  win.webContents.on('dom-ready', () => {
    win.webContents.executeJavaScript(`
      (() => {
        try { Object.defineProperty(navigator, 'webdriver', { get: () => undefined }) } catch {}
        try { Object.defineProperty(navigator, 'plugins', { get: () => [{ name: 'PDF Viewer' }, { name: 'Chrome PDF Viewer' }, { name: 'Chromium PDF Viewer' }] }) } catch {}
        try { Object.defineProperty(navigator, 'languages', { get: () => ['pt-BR', 'pt', 'en-US', 'en'] }) } catch {}
        try { window.chrome = window.chrome || { runtime: {}, app: {}, csi: () => {}, loadTimes: () => ({}) } } catch {}
      })();
    `).catch(() => {})
  })

  await win.loadURL(loginUrl)

  // Promise que resolve quando o login eh detectado ou rejeita por timeout/cancelamento
  return new Promise((resolve, reject) => {
    let settled = false
    let poll = null

    const timer = setTimeout(() => {
      if (settled) return
      settled = true
      cleanup()
      reject(new Error('Tempo esgotado — login nao concluido em 5 minutos.'))
    }, LOGIN_TIMEOUT_MS)

    const onClosed = () => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      clearInterval(poll)
      reject(new Error('Janela de login fechada antes de concluir.'))
    }

    function cleanup() {
      clearInterval(poll)
      win.removeListener('closed', onClosed)
      try { if (!win.isDestroyed()) win.close() } catch {}
    }

    win.on('closed', onClosed)

    // A cada navegacao, checa se logou de verdade.
    win.webContents.on('did-navigate', (_e, url) => checkLogin(url))
    win.webContents.on('did-navigate-in-page', (_e, url) => checkLogin(url))

    // Poll de seguranca: alguns passos (2FA, "salvar login") trocam de tela via
    // SPA sem disparar evento de navegacao confiavel. Repolla a URL atual ate logar.
    poll = setInterval(() => {
      if (settled) return
      try { checkLogin(win.webContents.getURL()) } catch {}
    }, 2500)

    async function checkLogin(currentUrl) {
      if (settled) return
      try {
        const u = new URL(currentUrl)

        if (isYt) {
          // Para YT: nao basta sair da pagina de login — precisa estar de verdade logado.
          // Detecta via presenca de cookies de auth do Google (SAPISID + LOGIN_INFO da YT).
          // Se ainda esta em accounts.google.com, claramente nao logou ainda.
          if (u.hostname.includes('accounts.google.com') || u.pathname.includes('/signin')) return
          await new Promise(r => setTimeout(r, 1500))
          const cookies = await ses.cookies.get({})
          const hasAuth = cookies.some(c =>
            (c.domain.includes('youtube.com') && c.name === 'LOGIN_INFO') ||
            (c.domain.includes('google.com') && c.name === 'SAPISID')
          )
          if (!hasAuth) return // ainda nao logou (so esta navegando youtube anonimo)
          await saveStorageState(cookies, sessionFile, false)
          const netscapePath = path.join(dataDir, 'sessions', `yt-cookies-${username}.txt`)
          await saveCookiesNetscape(cookies, netscapePath)
          settled = true
          clearTimeout(timer)
          cleanup()
          resolve({ ok: true, sessionFile })
          return
        }

        // ── IG / TikTok ────────────────────────────────────────────────────────
        // NAO confiar na URL: IG/TT gravam cookies anonimos (csrftoken, mid, ttwid,
        // msToken...) ANTES do login, e durante o codigo de verificacao / 2FA o site
        // navega pra paginas fora de /login. Se confiarmos so na URL, fechamos a janela
        // no meio da verificacao. So consideramos logado quando o cookie de SESSAO real
        // (`sessionid`) existe — ele so eh emitido APOS concluir o codigo de verificacao.
        await new Promise(r => setTimeout(r, 800))
        const cookies = await ses.cookies.get({})
        const authDomain = isInsta ? 'instagram.com' : 'tiktok.com'
        const hasSession = cookies.some(c =>
          c.name === 'sessionid' &&
          c.value && c.value.length >= 8 &&
          (c.domain || '').includes(authDomain)
        )
        if (!hasSession) return // ainda logando (credenciais / 2FA / captcha) — mantem janela aberta

        await saveStorageState(cookies, sessionFile, isInsta)

        settled = true
        clearTimeout(timer)
        cleanup()
        resolve({ ok: true, sessionFile })
      } catch (err) {
        // Continua esperando — pode ser navegacao parcial
      }
    }
  })
}

// Salva cookies em formato Netscape (cookies.txt) pra yt-dlp consumir.
// Formato: domain TAB flag TAB path TAB secure TAB expiration TAB name TAB value
async function saveCookiesNetscape(electronCookies, outFile) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by PostMaster', '']
  for (const c of electronCookies) {
    // Filtra so cookies relevantes pra YouTube/Google
    if (!c.domain.match(/google|youtube/i)) continue
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain.replace(/^www\./, '')}`
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const path = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expires = Math.floor(c.expirationDate || (Date.now()/1000 + 365*86400))
    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`)
  }
  fs.writeFileSync(outFile, lines.join('\n'), 'utf-8')
}

// Converte cookies do Electron pro formato storageState do Playwright
async function saveStorageState(electronCookies, outFile, isInsta) {
  const playwrightCookies = electronCookies.map(c => ({
    name: c.name,
    value: c.value,
    domain: c.domain.startsWith('.') ? c.domain : `.${c.domain.replace(/^www\./, '')}`,
    path: c.path || '/',
    expires: c.expirationDate || -1,
    httpOnly: !!c.httpOnly,
    secure: !!c.secure,
    sameSite: ({ unspecified: 'Lax', no_restriction: 'None', lax: 'Lax', strict: 'Strict' }[c.sameSite] || 'Lax'),
  }))

  const state = {
    cookies: playwrightCookies,
    origins: [], // Localstorage nao eh transferivel entre Electron e Playwright facilmente — IG/TT funcionam so com cookies
  }

  fs.writeFileSync(outFile, JSON.stringify(state, null, 2))
}
